### ISSUE TITLE
Plan: merge changes for current CPAN release + new corrections

### ISSUE THREAD

**Issue by polettix** [briandfoy/http-cookies-mozilla#1]
In 2011 I did the last release of this module coping with removal of a cookie by Usa Today. I did create a repository here in GH to do that, failing to both warn you and to back-propagate changes - which was a mistake on my side. Apologies for that, I probably did that in a hurry at that time. The change is here: https://github.com/polettix/HTTP-Cookies-Mozilla/commit/19351539f66479b23cab3ced265584e444c6b065

If you agree, I can fork this repo - where I see you did a lot of work - and pull in that change. This should make this repo up to date with respect to what's currently on CPAN.

After that, I'd like to correct a test file (save.t) because it can fail in a corner case (happening if the test is run immediately before the change of the second in what time() gives back) as it happened recently (see http://www.cpantesters.org/cpan/report/69686fa0-c463-11e5-ae3b-d62d7de6d7be).

**Comment by briandfoy** [comment]
For the first issue, I updated the expiry time on the cookie. I want the domains to have a different number of cookies so they return different counts. This way we don't accidentally create a counting thing that always returns the same number.

For the second issue, investigate that and lets see what you find. I tried to make it happen, and I think it's related to something in HTTP::Cookies and how it converts from max_age back to expires. In that set_cookie, it adds time() after we've subtracted it. I'm trying to reliably reproduce this in the expiry_time_bug branch by overriding time().

**Comment by polettix** [comment]
Re 1, it totally make sense to just update the expiration time.

Re 2, as you guessed it's a race condition between our calculation of max_age and HTTP::Cookies calculation of the expiration time. If you try this commit it will become easy to see: https://github.com/polettix/HTTP-Cookies-Mozilla/commit/995964ec27d5c892e1172cdcb12e211859ad6502 - it's just expanding the time between what's returned by _now() and the back-calculation by HTTP::Cookies.

The change you did with _now() just makes this "bug" much less likely to happen (it was probably already quite difficult to hit before) because the calculation happens at the very last. There is still a race condition though.

My opinion is that we must just live with this and do a workaround in save.t to allow for a range of values instead of exact matching on that field. I'll propose something in a PR.

**Comment by polettix** [comment]
PR #2 has my proposed fixes.
